name: Update Apple Health Record

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'date time'
        required: true
      move:
        description: 'move value'
        required: true

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      # from https://github.com/pdm-project/pdm/blob/main/.github/workflows/ci.yml
      - name: Set Variables
        id: set_variables
        shell: bash
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run sync apple health script
        run: |
          python -m github_poster apple_health --apple_health_date ${{ github.event.inputs.time }} --apple_health_values ${{ github.event.inputs.move }} --apple_health_record_type move --me ${{ env.ME }}

      - name: Push new postger
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'update new poster' || echo "nothing to commit"
          git push || echo "nothing to push"
